name: Rust
permissions:
  contents: write

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: Swatinem/rust-cache@v2
      with:
        # The cargo workspaces and target directory configuration.
        # These entries are separated by newlines and have the form
        # `$workspace -> $target`. The `$target` part is treated as a directory
        # relative to the `$workspace` and defaults to "target" if not explicitly given.
        # default: ". -> target"
        workspaces: ". -> target"
        cache-all-crates: "true"

    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Install wasm-pack
      run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
    - name: Build wasm
      run: wasm-pack build --target web ./chocolate_libvm

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v4
    - name: Install wasm-pack
      run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
    - name: Build wasm
      run: wasm-pack build --target web ./chocolate_libvm --release
    - name: Prepare directory
      run: rm -rf ./chocolate_libvm/web-build && mkdir ./chocolate_libvm/web-build && cp -r ./chocolate_libvm/pkg ./chocolate_libvm/web-build && cp ./chocolate_libvm/index.html ./chocolate_libvm/web-build && rm ./chocolate_libvm/web-build/pkg/.gitignore
    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        branch: gh-pages
        folder: chocolate_libvm/web-build
        clean: true